version: "3.9"

networks: 
  theatre:
    driver: bridge


services: 
  db_postgre:
    image: registry.hiriko.local:5000/postgres:11.2-alpine
    container_name: dev_db
    restart: always
    ports: 
      - "5432:5432"
    volumes: 
      - ./dubbing.sql:/docker-entrypoint-initdb.d/dubbing.sql
    # environment: 
    #   - POSTGRES_DB=dubbing
    #   - POSTGRES_USER=dubbing
    #   - POSTGRES_PASSWORD=dubbing
    networks: 
      - theatre
  
  back:
    restart: always
    container_name: dev_back
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5000:80"
    depends_on: 
        - "db_postgre"
    command: ["./wait-for-postgresql.sh", "db_postgre", "python", "app.py"]
    networks: 
      - theatre
    
    
