version: "3.9"

services: 
  db:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=dubbing
      - POSTGRES_USER=dubbing
      - POSTGRES_PASSWORD=dubbing
  front:
    build: ./LvivPuppetTheatreFRONT
    ports:
      - "3000:3000"
    depends_on: 
      - "back"
  back:
    build: ./LvivPuppetTheatreBACK
    ports: 
      - "5000:5000"
    depends_on: 
        - "db"
    
    