version: "3.9"

services: 
  db:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=dubbing
      - POSTGRES_USER=dubbing
      - POSTGRES_PASSWORD=dubbing
  back:
    build: .
    ports: "80:5000"
    depends_on: 
      - db
    