version: "3.9"

networks: 
  theatre:
    driver: bridge


services: 
  # db_postgre:
  #   images: postgresql:11.2-alpine
  #   restart: always
  #   ports: 
  #     - "5432:5432"
  #   volumes: 
  #     - ./var/pgdata:/var/lib/postgresql/data
  #   environment: 
  #     - POSTGRES_DB=dubbing
  #     - POSTGRES_USER=dubbing
  #     - POSTGRES_PASSWORD=dubbing
  #   networks: 
  #     - theatre
  back:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5000:80"
    # depends_on: 
    #     - "db_postgre"
    networks: 
      - theatre
    
    