version: "3.9"

networks: 
  theatre:
    driver: bridge


services: 
  db_postgre:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    volumes: 
      - ./dubbing.sql:/docker-entrypoint-initdb.d/dubbing.sql
      #добав sql для данних
    environment: 
      - POSTGRES_DB=dubbing
      - POSTGRES_USER=dubbing
      - POSTGRES_PASSWORD=dubbing
    networks: 
      - theatre
  # front:
  #   build: ./LvivPuppetTheatreFRONT
  #   ports:
  #     - "3000:3000"
  #   depends_on: 
  #     - "back"
  #   networks: 
  #     - theatre
  back:
    restart: always
    build: ./LvivPuppetTheatreBACK
    ports: 
      - "5000:80"
    depends_on: 
        - "db"
    networks: 
      - theatre
    
    